### ISSUE TITLE
`pvp_playerparticle_enable` would only work on cvar changed.

### ISSUE THREAD

**Issue by HotoCocoaco** [DosMike/TF2-PvP-OptIn#12]
The particle will be stopped only on `OnCVarChanged_UsePvPParticle`. Setting `pvp_playerparticle_enable` to 0 will still spawn particle on toggling pvp or player spawn.
There's no check for convar value when plugin is trying to spawn particle.
![image](https://user-images.githubusercontent.com/42245579/216286203-3d53e97a-8c78-40b2-84a0-057037490968.png)

**Comment by DosMike** [comment]
That convar was not intended for frequent change, but rather set once and keep. What's you use case for toggling that convar?

**Comment by HotoCocoaco** [comment]
Plugin doesn't check the convar's value when spawning particle that make it pretty much useless.

**Comment by HotoCocoaco** [comment]
![image](https://user-images.githubusercontent.com/42245579/216541308-3f48d01c-20d4-4d19-bb32-12142783c8cc.png)
Image is the particle still on my head when I turn off global pvp and the cvar is 0.

**Comment by HotoCocoaco** [comment]
This issue persists. But I cannot see anything wrong to the code rn. And the particle is still on every global pvp enabled players.
