### ISSUE TITLE
Plugin not loading with latest version of nativevote

### ISSUE THREAD

**Issue by BreadTeleporter** [DosMike/TF2-PvP-OptIn#14]
When I try to run the plugin, I get this error

[SM] Plugin pvpoptin.smx failed to reload: Native "NativeVote.SetTitle" was not found.

I am using the latest version of this plugin and NativeVote.
Do I need to use an older version?

**Comment by DosMike** [comment]
You're most probably using an outdated version of Native Votes, try the fork [linked on the ReadMe by sapphonie](https://github.com/sapphonie/sourcemod-nativevotes-updated)

**Comment by BreadTeleporter** [comment]
This fixed the problem, Thanks!
