### ISSUE TITLE
Recent update made the gameadata out of date.

### ISSUE THREAD

**Issue by NNinja1255** [DosMike/TF2-PvP-OptIn#19]
Are you able to update the gamedata for this plugin to work with the new update?

This is what was printed in the server console if you need it:
Could not hook INextBot::IsEnemy(this,CBaseEntity*). Bots will shoot at protected players!
Could not hook CZombieAttack::IsPotentiallyChaseable(this,CZombie*,CBaseCombatCharacter*)
Could not hook CHeadlessHatmanAttack::IsPotentiallyChaseable(this,CZombie*,CBaseCombatCharacter*)
Could not hook CMerasmusAttack::IsPotentiallyChaseable(this,CZombie*,CBaseCombatCharacter*)
Could not hook CEyeballBoss::FindClosestVisibleVictim(this)
Could not hook CObjectSentrygun::ValidTargetPlayer(CTFPlayer*,Vector*,Vector*). Whack!
Could not hook CObjectSentrygun::FoundTarget(CTFPlayer*,Vector*,bool). Turrets will always track zombies and bosses!
Could not hook CWeaponMedigun::AllowedToHealTarget(CBaseEntity*). Medic can grief PvP duels!
Could not hook CTFPlayerClassShared::SetCustomModel(). Players can hide their pvp state with vanity models!

**Comment by DosMike** [comment]
Please at least tell me the system/arch/binary you are running

**Comment by NNinja1255** [comment]
> Please at least tell me the system/arch/binary you are running Edit: because linux x32 still works (might require develop until i have validated windows sigs)

Windows x64. I am running the server at 32 bit though.
