### ISSUE TITLE
Gamedata needs updating again possibly?

### ISSUE THREAD

**Issue by gdfsgdfg** [DosMike/TF2-PvP-OptIn#21]
![image](https://github.com/user-attachments/assets/1925a68d-d2ad-4a3a-89c7-804f4210d94b)

**Comment by DosMike** [comment]
Thank you for the report.
I've been on a festival last week, I'll check it out.
In the meantime you can try to use the development branch (You might have to restart the server if you update to the dev version), that should have working sentry target filtering. I wanted to test that with bosses, but if sigs need updating I will preferably merge that into master and release a new version.
Build in the develop source tree is not up-to-date, here's a compiled dev version: [pvpoptin.smx.zip](https://github.com/user-attachments/files/16648243/pvpoptin.smx.zip)
