### ISSUE TITLE
Sentry has a chance to crash the server.

### ISSUE THREAD

**Issue by HotoCocoaco** [DosMike/TF2-PvP-OptIn#5]
https://crash.limetech.org/ugvqvqfqngbe

Find `pvpoptin.smx::Detour_CObjectSentrygun_FoundTarget` in even more raw.

**Comment by DosMike** [comment]
Can't see the raw, and the trace does not point to a plugin. Can you give me the raw?

**Comment by HotoCocoaco** [comment]
https://filetransfer.io/data-package/qBzL5zbR#link

minidump.

**Comment by DosMike** [comment]
I don't fully understand that crash yet.
Might be related to the discrepancy between code leak and compiled signature for FoundTarget.

**Comment by HotoCocoaco** [comment]
server_srv.so!CObjectSentrygun::GetEnemyAimPosition(CBaseEntity*) const + 0xf

**Comment by HotoCocoaco** [comment]
https://crash.limetech.org/uhajnnwsd7b2

**Comment by DosMike** [comment]
Hi, can you try the develop version?

**Comment by HotoCocoaco** [comment]
> Hi, can you try the develop version?

Installed. I will report if any related crash happens.

**Comment by HotoCocoaco** [comment]
develop branch error spam
```
L 08/29/2023 - 17:34:58: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 08/29/2023 - 17:34:58: [SM] Blaming: pvpoptin.smx
L 08/29/2023 - 17:34:58: [SM] Call stack trace:
L 08/29/2023 - 17:34:58: [SM]   [1] Line 1091, pvpoptin.sp::CanClientsPvP
L 08/29/2023 - 17:34:58: [SM]   [2] Line 211, pvpoptin/dtours.sp::SentryIsTargetBlocked
L 08/29/2023 - 17:34:58: [SM]   [3] Line 239, pvpoptin/dtours.sp::Detour_CObjectSentrygun_FindTarget
```

**Comment by DosMike** [comment]
Sorry it took so long...
The sentry target code is completely reworked, and seems to work better with player/bots/bosses. If you want you can check out the develop branch. If the issue persists, please re-open the issue :)
As for the next release, I want to properly block damage between bosses & players for unintentional hits, like splash damage.
