### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by dedimark** [DosMike/TF2-PvP-OptIn#9]
Sourcemod 1.11 - build 6919

//// pvpoptin.sp
//
// pvpoptin\api.sp(25) : warning 242: function "AskPluginLoad2" should return an explicit value
// pvpoptin\api.sp(53) : warning 242: function "Native_SetPlayerGlobal" should return an explicit value
// pvpoptin\api.sp(98) : warning 242: function "Native_ForcePlayerPair" should return an explicit value
// pvpoptin\api.sp(125) : warning 242: function "Native_SetMirrored" should return an explicit value
// pvpoptin\api.sp(138) : warning 242: function "Native_BanPlayer" should return an explicit value
// pvpoptin\api.sp(153) : warning 242: function "Native_UnbanPlayer" should return an explicit value
// pvpoptin\api.sp(153) : warning 242: function "Native_UnbanPlayer" should return an explicit value
// pvpoptin\api.sp(209) : warning 242: function "Notify_OnBanAdded" should return an explicit value
// pvpoptin\common.sp(53) : warning 228: enum multiplers are deprecated and will be removed in the next release
// pvpoptin\common.sp(63) : warning 228: enum multiplers are deprecated and will be removed in the next release
// pvpoptin.sp(189) : warning 204: symbol is assigned a value that is never used: "depMirrorDamage"
// pvpoptin.sp(396) : warning 209: function has explicit 'int' tag but does not return a value
// pvpoptin.sp(579) : warning 209: function has explicit 'int' tag but does not return a value
// pvpoptin.sp(816) : warning 209: function has explicit 'int' tag but does not return a value
// pvpoptin.sp(864) : warning 209: function has explicit 'int' tag but does not return a value
// pvpoptin.sp(864) : warning 209: function has explicit 'int' tag but does not return a value
// Code size:         112828 bytes
// Data size:         51212 bytes
// Stack/heap size:      18516 bytes
// Total requirements:  182556 bytes
//
// 16 Warnings.
//
// Compilation Time: 1.05 sec

Can you fix please?

**Comment by DosMike** [comment]
That's just warnings, not errors. If you compile without `-E`/`--warnings-as-errors` it builds and runs fine.
Iirc the master branch currently still targets SM 1.10.
If you're annoyed or irritated by warnings, you'll have to wait unil the next feature update.
